# Site settings
title: Brian Maier Jr.
email: brimaidesigns@gmail.com
description: Another butcher in the meatmarket
baseurl: "/portfolio-new"
url: ""
twitter_username: brianmaierjr
github_username:  brianmaierjr
dribbble_username: brianmaierjr

sass:
    style: :compressed

# Build settings
markdown: kramdown
