# Site settings
title: Brian Maier Jr.
email: brimaidesigns@gmail.com
description: Another butcher in the meat market
baseurl: "http://brianmaierjr.com"
permalinks: pretty

# Build settings
markdown: kramdown
